name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        
    - name: Install dependencies and update lockfile
      run: yarn install
      
    - name: Commit yarn.lock
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add yarn.lock
        git diff --quiet && git diff --staged --quiet || git commit -m "chore: update yarn.lock"
      continue-on-error: true
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      continue-on-error: true
      
    - name: Run tests
      run: yarn test
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
      
    - name: Type check
      run: yarn typecheck
      
    - name: Build
      run: yarn build